# Generated by Django 3.2.16 on 2023-01-09 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('virat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_name', models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='midday',
            name='row',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='virat.night'),
        ),
    ]
